### ISSUE TITLE
Comments inside slist

### ISSUE THREAD

**Issue by larsewi** [miekg/cf#27]
When using comments inside slists, three leading spaces are printed in front of all comments trailing an element, except for the comment trailing the last element. I would expect two leading spaces to be printed for all elements.

```
$ cat > test.cf
body common control {
    bundlesequence => {
        "bogus", # first
        "doofus", # last
    };
}
$ cffmt test.cf | sed "s/ /./g" # Swap spaces with dots
body.common.control
{
..bundlesequence.=>.{."bogus",...#.first
......................"doofus"..#.last
.......................};
}
```

When temporarily commenting out bundles from a bundle sequence, they appear on the line above. It would be more convenient if they stayed on the same line, so that I could easily uncomment them.

```
$ cat > test.cf
body common control {
    bundlesequence => {
        # "foo",
        "bogus",
        # "bar",
        "doofus",
    };
}
$ cffmt test.cf
body common control
{
  bundlesequence => {   "# foo",
                      "bogus",   "# bar",
                      "doofus" };
}
```

**Comment by miekg** [comment]
the identing is deliberate, except the first one, that should not really be indented.

List like this are handy, and hard to detect (in the current lexer/parser).  As a work around I implemented: `# cffmt:list-nl` that puts every item on a new line, except currently this is only acted upon in a constraint.

Maybe another heuristic can't be thought off to make this detectable and make cffmt do the right thing?

**Comment by larsewi** [comment]
Maybe you can add "newline" as a token to the lexer? Then tokens preceded by a newline token can be pretty printed differently than tokens preceded by any other token.

**Comment by miekg** [comment]
Actually tried your suggestion already, and yes, of course, this can be done. However the current lexer throws away all whitespace (chroma.Text tokens actually), this would be a rather big change, because now everywhere a Text node can crop up (same problem as Comments actually).  (Allowing chroma.Text tokens would prolly be the correct and right thing to do here)

I can prolly still detect some of these cases without resorting to allowing to Text tokens, and `cffmt:list-nl` would then be an (ugly) escape hatch. I'll try a bunch of things
